"""add is_indexed to document_metadata

Revision ID: 1e71229512ea
Revises: a610fd9b73d1
Create Date: 2026-08-07 13:06:29.853301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e71229512ea'
down_revision: Union[str, None] = 'a610fd9b73d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_metadata',
        sa.Column('is_indexed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_metadata', 'is_indexed')
    # ### end Alembic commands ###
