"""add source to messages

Revision ID: 266ca1bc39ea
Revises: 1e71229512ea
Create Date: 2026-08-08 06:30:37.570745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266ca1bc39ea'
down_revision: Union[str, None] = '1e71229512ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'source')
    # ### end Alembic commands ###
