"""add is_verified to messages

Revision ID: 35452b691406
Revises: 266ca1bc39ea
Create Date: 2026-08-12 12:43:12.579496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35452b691406'
down_revision: Union[str, None] = '266ca1bc39ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_verified')
    # ### end Alembic commands ###
