"""add is_scanned to document_metadata

Revision ID: a610fd9b73d1
Revises: f4d8c2312454
Create Date: 2026-08-07 06:47:10.742861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a610fd9b73d1'
down_revision: Union[str, None] = 'f4d8c2312454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('is_scanned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_metadata', 'is_scanned')
    # ### end Alembic commands ###
